version: '2'
services:
  bsbang-crawler:
    build:
      context: .
      dockerfile: DockerFiles/bsbang-crawler/Dockerfile
    links:
      - mar-ref-solr
    image: bsbang-crawler:latest

  biosd-curator:
    build:
      context: .
      dockerfile: DockerFiles/biosd-curator/Dockerfile
    image: biosd-curator:latest

  mar-ref-solr:
    image: solr:6.6.2-alpine
    ports:
      - "8984:8983"
    volumes: 
      - ./data/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - bsbang

  mar-ref-site:
    image: python:2.7
    ports:
      - "8080:8080"
    working_dir: /MarRef/
    volumes:
      - ./site/src:/MarRef
    entrypoint:
      - python
      - -m
      - SimpleHTTPServer
      - "8080"

  bsbc-setup:
    image: bsbang-crawler:latest
    links:
      - mar-ref-solr
    working_dir: /crawler/setup
    volumes:
      - ./data/crawler:/crawler/data/
#    command: bash -c "rm /crawler/data/crawl.db && touchpython ./bsbang-setup-sqlite.py && python ./bsbang-setup-solr.py ../conf/bsbang-solr-setup.xml"
    entrypoint: ./setup.sh

  bsbc-crawl:
    image: bsbang-crawler:latest
    volumes:
      - ./data/crawler:/crawler/data/
      - ./sitemaps:/crawler/sitemaps
    command: python bsbang-crawl.py data/crawl.db sitemaps/links.txt

  bsbc-extract:
    image: bsbang-crawler:latest
    volumes:
      - ./data/crawler:/crawler/data/
    command: python bsbang-extract.py data/crawl.db

  bsbc-index:
    image: bsbang-crawler:latest
    links:
      - mar-ref-solr
    volumes:
      - ./data/crawler:/crawler/data/
    command: python bsbang-index.py data/crawl.db

  biosd-curate:
    image: biosd-curator:latest
    volumes:
      - ./data/crawler:/curator/data
    networks:
      - biosamplesv4_default
    command: python biosamples-curation.py data/crawl.db http://biosamples-webapps-core:8080/biosamples

networks:
    biosamplesv4_default:
        external: true
