version: '2'
services:
  mar-ref-solr:
    image: solr:6.6.2-alpine
    ports:
      - "8983:8983"
    volumes: 
      - ./data/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - bsbang

  mar-ref-site:
    image: python:2.7
    ports:
      - "8080:8080"
    working_dir: /MarRef/
    volumes:
      - ./site/src:/MarRef
    entrypoint:
      - python
      - -m
      - SimpleHTTPServer
      - "8080"

  bsbang-crawler:
    build: .
    image: bsbang-crawler:latest
    links:
      - mar-ref-solr
    volumes:
      - ./data/crawler/data:/crawler/data/
